services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:3000
    volumes:
      - ./docuseal:/data/docuseal
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/docuseal
    extra_hosts:
      - 'host.docker.internal:host-gateway'
